// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAbilities():Promise<Array<Record<string, any>>>;

export function GetLogPath():Promise<string>;

export function GetStats():Promise<Record<string, any>>;

export function GetTargets():Promise<Array<Record<string, any>>>;

export function OpenDevTools():Promise<string>;

export function ResetStats():Promise<string>;

export function StartMonitoring():Promise<string>;

export function StopMonitoring():Promise<string>;
