// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAbilities() {
  return window['go']['app']['App']['GetAbilities']();
}

export function GetLogPath() {
  return window['go']['app']['App']['GetLogPath']();
}

export function GetStats() {
  return window['go']['app']['App']['GetStats']();
}

export function GetTargets() {
  return window['go']['app']['App']['GetTargets']();
}

export function OpenDevTools() {
  return window['go']['app']['App']['OpenDevTools']();
}

export function ResetStats() {
  return window['go']['app']['App']['ResetStats']();
}

export function StartMonitoring() {
  return window['go']['app']['App']['StartMonitoring']();
}

export function StopMonitoring() {
  return window['go']['app']['App']['StopMonitoring']();
}
