name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.5'
        
    - name: Install Wails
      run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
      
    - name: Add Wails to PATH
      run: echo "$env:GOPATH\bin" >> $env:GITHUB_PATH
      
    - name: Build application
      run: wails build -platform windows/amd64
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: aocdpsmetr-windows
        path: build/bin/aocdpsmetr.exe
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: build/bin/aocdpsmetr.exe
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
